name: Semgrep

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - qa
    types:
      - opened
      - synchronize
      - reopened

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip-Scan]') }}
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_GITHUB_APP_TOKEN: ${{ secrets.SEMGREP_GITHUB_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep ci
